const initialState = {
  pointsForDNF: false,
  websiteName: "jrc-results",
  subfolderName: "modern",
  showLivePoints: true,
  showLivePointsDaysRemaining: 4,
  showCarNameAsTextInResults: true,
  useStandingsForHome: true,
  backgroundStyle:
    "background-image: linear-gradient(#2193b0, #6dd5ed); background-size: cover; background-repeat: no-repeat; background-attachment: fixed;",
  logo: "JRC.png",
  siteTitlePrefix: "JRC Modern",
  divisions: {
    modern2306: {
      divisionName: "modern2306",
      displayName: "JRC Modern",
      disableSameCarValidation: true,
      clubs: [{ clubId: "387957", championshipIds: ["755106"] }],
      events: [],
      points: {
        powerStage: [],
        overall: [
          35,
          29,
          26,
          23,
          20,
          18,
          16,
          14,
          12,
          11,
          10,
          9,
          8,
          7,
          6,
          5,
          4,
          3,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ]
      },
      manualResults: []
    }
  },
  historicalSeasonLinks: [
    {
      name: "Modern 2021-06",
      href: "/modern/modern-1"
    }
  ]
};

module.exports = initialState;
