on: workflow_dispatch

jobs:
  publish-results:
    env:
      DIRT_USERNAME: ${{ secrets.DIRT_USERNAME }}
      DIRT_PASSWORD: ${{ secrets.DIRT_PASSWORD }}
      RACENET_USERNAME: ${{ secrets.RACENET_USERNAME }}
      RACENET_PASSWORD: ${{ secrets.RACENET_PASSWORD }}
      DIRT_AWS_ACCESS_KEY: ${{ secrets.DIRT_AWS_ACCESS_KEY }}
      DIRT_AWS_SECRET_ACCESS_KEY: ${{ secrets.DIRT_AWS_SECRET_ACCESS_KEY }}
      GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
      GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
      DEBUG: tkidman:*
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: CLUB=jrc-themed node  --unhandled-rejections=strict ./runner.js
      # - run: CLUB=jrc node --unhandled-rejections=strict ./runner.js
  